### ISSUE TITLE
Custom canvas Apply CSS in text for preview

### ISSUE THREAD

**Issue by jalpab** [aurigma/CustomersCanvasSamples#12]
Hello
Currently, I am working with customer Canvas,
and I want to manipulate design within my canvas

So in the given code, I am calling Canvas's API For generating canvas preview.

<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://my.accucanvas.com/apps/design-editor/stable/api/Preview/GeneratePreview',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS =>'{
    "previewOptions": {
        "maxWidth": 1875,
        "maxHeight": 1275
    },
    "itemsData": {
      
        "Plain text": {
            "text": "dev<br/>aaa<br/>22",
            "font": {
                "size": 40.5
            },
            color: "rgb(255, 0, 100)",
        }
    },
    "productDefinitions": [
            "Campaign1_1"
      
    ],
    "userId": "Touchcard_1"
}',
  CURLOPT_HTTPHEADER => array(
    'X-CustomersCanvasAPIKey: API_KEY_HERE',
    'Content-Type: application/json',
    'Cookie: ASP.NET_SessionId=SESSION_ID_HERE'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo "<pre>";
print_r(json_decode($response,true));

Here, I want Add css and in text but the API consider as a plain text can you please guide me how to fix this?

**Comment by asimontsev** [comment]
Thanks for reaching out! If you are our customer, we are happy to help you out, please submit a support ticket on https://customerscanvas.com/account/cases and our support team will get back to you as soon as possible.
